// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: manager.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Job status enumeration
type JobStatus int32

const (
	JobStatus_JOB_STATUS_UNKNOWN   JobStatus = 0
	JobStatus_JOB_STATUS_PENDING   JobStatus = 1
	JobStatus_JOB_STATUS_RUNNING   JobStatus = 2
	JobStatus_JOB_STATUS_COMPLETED JobStatus = 3
	JobStatus_JOB_STATUS_FAILED    JobStatus = 4
	JobStatus_JOB_STATUS_CANCELLED JobStatus = 5
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_UNKNOWN",
		1: "JOB_STATUS_PENDING",
		2: "JOB_STATUS_RUNNING",
		3: "JOB_STATUS_COMPLETED",
		4: "JOB_STATUS_FAILED",
		5: "JOB_STATUS_CANCELLED",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_UNKNOWN":   0,
		"JOB_STATUS_PENDING":   1,
		"JOB_STATUS_RUNNING":   2,
		"JOB_STATUS_COMPLETED": 3,
		"JOB_STATUS_FAILED":    4,
		"JOB_STATUS_CANCELLED": 5,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_manager_proto_enumTypes[0].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_manager_proto_enumTypes[0]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{0}
}

// Resource requirements
type ResourceRequirements struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           string                 `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        string                 `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRequirements) Reset() {
	*x = ResourceRequirements{}
	mi := &file_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRequirements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRequirements) ProtoMessage() {}

func (x *ResourceRequirements) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRequirements.ProtoReflect.Descriptor instead.
func (*ResourceRequirements) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceRequirements) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *ResourceRequirements) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

// Resource limits and requests
type Resources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      *ResourceRequirements  `protobuf:"bytes,1,opt,name=requests,proto3" json:"requests,omitempty"`
	Limits        *ResourceRequirements  `protobuf:"bytes,2,opt,name=limits,proto3" json:"limits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resources) Reset() {
	*x = Resources{}
	mi := &file_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resources) ProtoMessage() {}

func (x *Resources) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resources.ProtoReflect.Descriptor instead.
func (*Resources) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{1}
}

func (x *Resources) GetRequests() *ResourceRequirements {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *Resources) GetLimits() *ResourceRequirements {
	if x != nil {
		return x.Limits
	}
	return nil
}

// Preprocessing configuration
type PreprocessingConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BatchSize       int32                  `protobuf:"varint,1,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	MaxLength       int32                  `protobuf:"varint,2,opt,name=max_length,json=maxLength,proto3" json:"max_length,omitempty"`
	NSamples        int32                  `protobuf:"varint,3,opt,name=n_samples,json=nSamples,proto3" json:"n_samples,omitempty"`
	ParallelWorkers int32                  `protobuf:"varint,4,opt,name=parallel_workers,json=parallelWorkers,proto3" json:"parallel_workers,omitempty"`
	ChunkSize       int32                  `protobuf:"varint,5,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PreprocessingConfig) Reset() {
	*x = PreprocessingConfig{}
	mi := &file_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreprocessingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreprocessingConfig) ProtoMessage() {}

func (x *PreprocessingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreprocessingConfig.ProtoReflect.Descriptor instead.
func (*PreprocessingConfig) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{2}
}

func (x *PreprocessingConfig) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *PreprocessingConfig) GetMaxLength() int32 {
	if x != nil {
		return x.MaxLength
	}
	return 0
}

func (x *PreprocessingConfig) GetNSamples() int32 {
	if x != nil {
		return x.NSamples
	}
	return 0
}

func (x *PreprocessingConfig) GetParallelWorkers() int32 {
	if x != nil {
		return x.ParallelWorkers
	}
	return 0
}

func (x *PreprocessingConfig) GetChunkSize() int32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

// Data locations configuration
type DataLocations struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locations     []string               `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	Strategy      string                 `protobuf:"bytes,2,opt,name=strategy,proto3" json:"strategy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataLocations) Reset() {
	*x = DataLocations{}
	mi := &file_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataLocations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataLocations) ProtoMessage() {}

func (x *DataLocations) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataLocations.ProtoReflect.Descriptor instead.
func (*DataLocations) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{3}
}

func (x *DataLocations) GetLocations() []string {
	if x != nil {
		return x.Locations
	}
	return nil
}

func (x *DataLocations) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

// CSD configuration
type CSDConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	DevicePath    string                 `protobuf:"bytes,2,opt,name=device_path,json=devicePath,proto3" json:"device_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CSDConfig) Reset() {
	*x = CSDConfig{}
	mi := &file_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CSDConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSDConfig) ProtoMessage() {}

func (x *CSDConfig) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSDConfig.ProtoReflect.Descriptor instead.
func (*CSDConfig) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{4}
}

func (x *CSDConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CSDConfig) GetDevicePath() string {
	if x != nil {
		return x.DevicePath
	}
	return ""
}

// Node scheduling configuration
type NodeScheduling struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	NodeSelector  map[string]string      `protobuf:"bytes,2,rep,name=node_selector,json=nodeSelector,proto3" json:"node_selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeScheduling) Reset() {
	*x = NodeScheduling{}
	mi := &file_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeScheduling) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeScheduling) ProtoMessage() {}

func (x *NodeScheduling) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeScheduling.ProtoReflect.Descriptor instead.
func (*NodeScheduling) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{5}
}

func (x *NodeScheduling) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *NodeScheduling) GetNodeSelector() map[string]string {
	if x != nil {
		return x.NodeSelector
	}
	return nil
}

// Job configuration
type JobConfig struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Parallelism             int32                  `protobuf:"varint,1,opt,name=parallelism,proto3" json:"parallelism,omitempty"`
	Completions             int32                  `protobuf:"varint,2,opt,name=completions,proto3" json:"completions,omitempty"`
	BackoffLimit            int32                  `protobuf:"varint,3,opt,name=backoff_limit,json=backoffLimit,proto3" json:"backoff_limit,omitempty"`
	TtlSecondsAfterFinished int32                  `protobuf:"varint,4,opt,name=ttl_seconds_after_finished,json=ttlSecondsAfterFinished,proto3" json:"ttl_seconds_after_finished,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *JobConfig) Reset() {
	*x = JobConfig{}
	mi := &file_manager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobConfig) ProtoMessage() {}

func (x *JobConfig) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobConfig.ProtoReflect.Descriptor instead.
func (*JobConfig) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{6}
}

func (x *JobConfig) GetParallelism() int32 {
	if x != nil {
		return x.Parallelism
	}
	return 0
}

func (x *JobConfig) GetCompletions() int32 {
	if x != nil {
		return x.Completions
	}
	return 0
}

func (x *JobConfig) GetBackoffLimit() int32 {
	if x != nil {
		return x.BackoffLimit
	}
	return 0
}

func (x *JobConfig) GetTtlSecondsAfterFinished() int32 {
	if x != nil {
		return x.TtlSecondsAfterFinished
	}
	return 0
}

// Job submission request
type SubmitJobRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JobId           string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobName         string                 `protobuf:"bytes,2,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	Namespace       string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Image           string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	ImagePullPolicy string                 `protobuf:"bytes,5,opt,name=image_pull_policy,json=imagePullPolicy,proto3" json:"image_pull_policy,omitempty"`
	DataPath        string                 `protobuf:"bytes,6,opt,name=data_path,json=dataPath,proto3" json:"data_path,omitempty"`
	OutputPath      string                 `protobuf:"bytes,7,opt,name=output_path,json=outputPath,proto3" json:"output_path,omitempty"`
	TargetNode      string                 `protobuf:"bytes,8,opt,name=target_node,json=targetNode,proto3" json:"target_node,omitempty"`
	Resources       *Resources             `protobuf:"bytes,9,opt,name=resources,proto3" json:"resources,omitempty"`
	Preprocessing   *PreprocessingConfig   `protobuf:"bytes,10,opt,name=preprocessing,proto3" json:"preprocessing,omitempty"`
	DataLocations   *DataLocations         `protobuf:"bytes,11,opt,name=data_locations,json=dataLocations,proto3" json:"data_locations,omitempty"`
	Csd             *CSDConfig             `protobuf:"bytes,12,opt,name=csd,proto3" json:"csd,omitempty"`
	NodeScheduling  *NodeScheduling        `protobuf:"bytes,13,opt,name=node_scheduling,json=nodeScheduling,proto3" json:"node_scheduling,omitempty"`
	JobConfig       *JobConfig             `protobuf:"bytes,14,opt,name=job_config,json=jobConfig,proto3" json:"job_config,omitempty"`
	Labels          map[string]string      `protobuf:"bytes,15,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations     map[string]string      `protobuf:"bytes,16,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubmitJobRequest) Reset() {
	*x = SubmitJobRequest{}
	mi := &file_manager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobRequest) ProtoMessage() {}

func (x *SubmitJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobRequest.ProtoReflect.Descriptor instead.
func (*SubmitJobRequest) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{7}
}

func (x *SubmitJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SubmitJobRequest) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *SubmitJobRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SubmitJobRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *SubmitJobRequest) GetImagePullPolicy() string {
	if x != nil {
		return x.ImagePullPolicy
	}
	return ""
}

func (x *SubmitJobRequest) GetDataPath() string {
	if x != nil {
		return x.DataPath
	}
	return ""
}

func (x *SubmitJobRequest) GetOutputPath() string {
	if x != nil {
		return x.OutputPath
	}
	return ""
}

func (x *SubmitJobRequest) GetTargetNode() string {
	if x != nil {
		return x.TargetNode
	}
	return ""
}

func (x *SubmitJobRequest) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *SubmitJobRequest) GetPreprocessing() *PreprocessingConfig {
	if x != nil {
		return x.Preprocessing
	}
	return nil
}

func (x *SubmitJobRequest) GetDataLocations() *DataLocations {
	if x != nil {
		return x.DataLocations
	}
	return nil
}

func (x *SubmitJobRequest) GetCsd() *CSDConfig {
	if x != nil {
		return x.Csd
	}
	return nil
}

func (x *SubmitJobRequest) GetNodeScheduling() *NodeScheduling {
	if x != nil {
		return x.NodeScheduling
	}
	return nil
}

func (x *SubmitJobRequest) GetJobConfig() *JobConfig {
	if x != nil {
		return x.JobConfig
	}
	return nil
}

func (x *SubmitJobRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *SubmitJobRequest) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

// Job submission response
type SubmitJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	JobId         string                 `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	SubmittedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobResponse) Reset() {
	*x = SubmitJobResponse{}
	mi := &file_manager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobResponse) ProtoMessage() {}

func (x *SubmitJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitJobResponse) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{8}
}

func (x *SubmitJobResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubmitJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SubmitJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SubmitJobResponse) GetSubmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SubmittedAt
	}
	return nil
}

// Job status query request
type GetJobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusRequest) Reset() {
	*x = GetJobStatusRequest{}
	mi := &file_manager_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusRequest) ProtoMessage() {}

func (x *GetJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusRequest.ProtoReflect.Descriptor instead.
func (*GetJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{9}
}

func (x *GetJobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// Job status query response
type GetJobStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status         JobStatus              `protobuf:"varint,2,opt,name=status,proto3,enum=manager.JobStatus" json:"status,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	StartTime      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	CompletionTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=completion_time,json=completionTime,proto3" json:"completion_time,omitempty"`
	OutputPath     string                 `protobuf:"bytes,6,opt,name=output_path,json=outputPath,proto3" json:"output_path,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetJobStatusResponse) Reset() {
	*x = GetJobStatusResponse{}
	mi := &file_manager_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusResponse) ProtoMessage() {}

func (x *GetJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusResponse.ProtoReflect.Descriptor instead.
func (*GetJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{10}
}

func (x *GetJobStatusResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetJobStatusResponse) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNKNOWN
}

func (x *GetJobStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetJobStatusResponse) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetJobStatusResponse) GetCompletionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletionTime
	}
	return nil
}

func (x *GetJobStatusResponse) GetOutputPath() string {
	if x != nil {
		return x.OutputPath
	}
	return ""
}

func (x *GetJobStatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Job cancellation request
type CancelJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobRequest) Reset() {
	*x = CancelJobRequest{}
	mi := &file_manager_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobRequest) ProtoMessage() {}

func (x *CancelJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobRequest.ProtoReflect.Descriptor instead.
func (*CancelJobRequest) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{11}
}

func (x *CancelJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CancelJobRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Job cancellation response
type CancelJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CancelledAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=cancelled_at,json=cancelledAt,proto3" json:"cancelled_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobResponse) Reset() {
	*x = CancelJobResponse{}
	mi := &file_manager_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobResponse) ProtoMessage() {}

func (x *CancelJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobResponse.ProtoReflect.Descriptor instead.
func (*CancelJobResponse) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{12}
}

func (x *CancelJobResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CancelJobResponse) GetCancelledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CancelledAt
	}
	return nil
}

// Node resource information
type NodeResources struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeName        string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	CpuCapacity     string                 `protobuf:"bytes,2,opt,name=cpu_capacity,json=cpuCapacity,proto3" json:"cpu_capacity,omitempty"`
	MemoryCapacity  string                 `protobuf:"bytes,3,opt,name=memory_capacity,json=memoryCapacity,proto3" json:"memory_capacity,omitempty"`
	CpuAvailable    string                 `protobuf:"bytes,4,opt,name=cpu_available,json=cpuAvailable,proto3" json:"cpu_available,omitempty"`
	MemoryAvailable string                 `protobuf:"bytes,5,opt,name=memory_available,json=memoryAvailable,proto3" json:"memory_available,omitempty"`
	RunningJobs     int32                  `protobuf:"varint,6,opt,name=running_jobs,json=runningJobs,proto3" json:"running_jobs,omitempty"`
	CsdEnabled      bool                   `protobuf:"varint,7,opt,name=csd_enabled,json=csdEnabled,proto3" json:"csd_enabled,omitempty"`
	CsdStatus       string                 `protobuf:"bytes,8,opt,name=csd_status,json=csdStatus,proto3" json:"csd_status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeResources) Reset() {
	*x = NodeResources{}
	mi := &file_manager_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeResources) ProtoMessage() {}

func (x *NodeResources) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeResources.ProtoReflect.Descriptor instead.
func (*NodeResources) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{13}
}

func (x *NodeResources) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *NodeResources) GetCpuCapacity() string {
	if x != nil {
		return x.CpuCapacity
	}
	return ""
}

func (x *NodeResources) GetMemoryCapacity() string {
	if x != nil {
		return x.MemoryCapacity
	}
	return ""
}

func (x *NodeResources) GetCpuAvailable() string {
	if x != nil {
		return x.CpuAvailable
	}
	return ""
}

func (x *NodeResources) GetMemoryAvailable() string {
	if x != nil {
		return x.MemoryAvailable
	}
	return ""
}

func (x *NodeResources) GetRunningJobs() int32 {
	if x != nil {
		return x.RunningJobs
	}
	return 0
}

func (x *NodeResources) GetCsdEnabled() bool {
	if x != nil {
		return x.CsdEnabled
	}
	return false
}

func (x *NodeResources) GetCsdStatus() string {
	if x != nil {
		return x.CsdStatus
	}
	return ""
}

// Node list request
type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CsdOnly       bool                   `protobuf:"varint,1,opt,name=csd_only,json=csdOnly,proto3" json:"csd_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_manager_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{14}
}

func (x *ListNodesRequest) GetCsdOnly() bool {
	if x != nil {
		return x.CsdOnly
	}
	return false
}

// Node list response
type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeResources       `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_manager_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{15}
}

func (x *ListNodesResponse) GetNodes() []*NodeResources {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_manager_proto protoreflect.FileDescriptor

const file_manager_proto_rawDesc = "" +
	"\n" +
	"\rmanager.proto\x12\amanager\x1a\x1fgoogle/protobuf/timestamp.proto\"@\n" +
	"\x14ResourceRequirements\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\tR\x03cpu\x12\x16\n" +
	"\x06memory\x18\x02 \x01(\tR\x06memory\"}\n" +
	"\tResources\x129\n" +
	"\brequests\x18\x01 \x01(\v2\x1d.manager.ResourceRequirementsR\brequests\x125\n" +
	"\x06limits\x18\x02 \x01(\v2\x1d.manager.ResourceRequirementsR\x06limits\"\xba\x01\n" +
	"\x13PreprocessingConfig\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x01 \x01(\x05R\tbatchSize\x12\x1d\n" +
	"\n" +
	"max_length\x18\x02 \x01(\x05R\tmaxLength\x12\x1b\n" +
	"\tn_samples\x18\x03 \x01(\x05R\bnSamples\x12)\n" +
	"\x10parallel_workers\x18\x04 \x01(\x05R\x0fparallelWorkers\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x05 \x01(\x05R\tchunkSize\"I\n" +
	"\rDataLocations\x12\x1c\n" +
	"\tlocations\x18\x01 \x03(\tR\tlocations\x12\x1a\n" +
	"\bstrategy\x18\x02 \x01(\tR\bstrategy\"F\n" +
	"\tCSDConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1f\n" +
	"\vdevice_path\x18\x02 \x01(\tR\n" +
	"devicePath\"\xbe\x01\n" +
	"\x0eNodeScheduling\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12N\n" +
	"\rnode_selector\x18\x02 \x03(\v2).manager.NodeScheduling.NodeSelectorEntryR\fnodeSelector\x1a?\n" +
	"\x11NodeSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb1\x01\n" +
	"\tJobConfig\x12 \n" +
	"\vparallelism\x18\x01 \x01(\x05R\vparallelism\x12 \n" +
	"\vcompletions\x18\x02 \x01(\x05R\vcompletions\x12#\n" +
	"\rbackoff_limit\x18\x03 \x01(\x05R\fbackoffLimit\x12;\n" +
	"\x1attl_seconds_after_finished\x18\x04 \x01(\x05R\x17ttlSecondsAfterFinished\"\xdb\x06\n" +
	"\x10SubmitJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x19\n" +
	"\bjob_name\x18\x02 \x01(\tR\ajobName\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x12*\n" +
	"\x11image_pull_policy\x18\x05 \x01(\tR\x0fimagePullPolicy\x12\x1b\n" +
	"\tdata_path\x18\x06 \x01(\tR\bdataPath\x12\x1f\n" +
	"\voutput_path\x18\a \x01(\tR\n" +
	"outputPath\x12\x1f\n" +
	"\vtarget_node\x18\b \x01(\tR\n" +
	"targetNode\x120\n" +
	"\tresources\x18\t \x01(\v2\x12.manager.ResourcesR\tresources\x12B\n" +
	"\rpreprocessing\x18\n" +
	" \x01(\v2\x1c.manager.PreprocessingConfigR\rpreprocessing\x12=\n" +
	"\x0edata_locations\x18\v \x01(\v2\x16.manager.DataLocationsR\rdataLocations\x12$\n" +
	"\x03csd\x18\f \x01(\v2\x12.manager.CSDConfigR\x03csd\x12@\n" +
	"\x0fnode_scheduling\x18\r \x01(\v2\x17.manager.NodeSchedulingR\x0enodeScheduling\x121\n" +
	"\n" +
	"job_config\x18\x0e \x01(\v2\x12.manager.JobConfigR\tjobConfig\x12=\n" +
	"\x06labels\x18\x0f \x03(\v2%.manager.SubmitJobRequest.LabelsEntryR\x06labels\x12L\n" +
	"\vannotations\x18\x10 \x03(\v2*.manager.SubmitJobRequest.AnnotationsEntryR\vannotations\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9d\x01\n" +
	"\x11SubmitJobResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x15\n" +
	"\x06job_id\x18\x03 \x01(\tR\x05jobId\x12=\n" +
	"\fsubmitted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vsubmittedAt\",\n" +
	"\x13GetJobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\xb9\x02\n" +
	"\x14GetJobStatusResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.manager.JobStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12C\n" +
	"\x0fcompletion_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0ecompletionTime\x12\x1f\n" +
	"\voutput_path\x18\x06 \x01(\tR\n" +
	"outputPath\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\"A\n" +
	"\x10CancelJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x86\x01\n" +
	"\x11CancelJobResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12=\n" +
	"\fcancelled_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vcancelledAt\"\xab\x02\n" +
	"\rNodeResources\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12!\n" +
	"\fcpu_capacity\x18\x02 \x01(\tR\vcpuCapacity\x12'\n" +
	"\x0fmemory_capacity\x18\x03 \x01(\tR\x0ememoryCapacity\x12#\n" +
	"\rcpu_available\x18\x04 \x01(\tR\fcpuAvailable\x12)\n" +
	"\x10memory_available\x18\x05 \x01(\tR\x0fmemoryAvailable\x12!\n" +
	"\frunning_jobs\x18\x06 \x01(\x05R\vrunningJobs\x12\x1f\n" +
	"\vcsd_enabled\x18\a \x01(\bR\n" +
	"csdEnabled\x12\x1d\n" +
	"\n" +
	"csd_status\x18\b \x01(\tR\tcsdStatus\"-\n" +
	"\x10ListNodesRequest\x12\x19\n" +
	"\bcsd_only\x18\x01 \x01(\bR\acsdOnly\"A\n" +
	"\x11ListNodesResponse\x12,\n" +
	"\x05nodes\x18\x01 \x03(\v2\x16.manager.NodeResourcesR\x05nodes*\x9e\x01\n" +
	"\tJobStatus\x12\x16\n" +
	"\x12JOB_STATUS_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12JOB_STATUS_PENDING\x10\x01\x12\x16\n" +
	"\x12JOB_STATUS_RUNNING\x10\x02\x12\x18\n" +
	"\x14JOB_STATUS_COMPLETED\x10\x03\x12\x15\n" +
	"\x11JOB_STATUS_FAILED\x10\x04\x12\x18\n" +
	"\x14JOB_STATUS_CANCELLED\x10\x052\xab\x02\n" +
	"\x10InstorageManager\x12B\n" +
	"\tSubmitJob\x12\x19.manager.SubmitJobRequest\x1a\x1a.manager.SubmitJobResponse\x12K\n" +
	"\fGetJobStatus\x12\x1c.manager.GetJobStatusRequest\x1a\x1d.manager.GetJobStatusResponse\x12B\n" +
	"\tCancelJob\x12\x19.manager.CancelJobRequest\x1a\x1a.manager.CancelJobResponse\x12B\n" +
	"\tListNodes\x12\x19.manager.ListNodesRequest\x1a\x1a.manager.ListNodesResponseB\x1eZ\x1cinstorage-operator/pkg/protob\x06proto3"

var (
	file_manager_proto_rawDescOnce sync.Once
	file_manager_proto_rawDescData []byte
)

func file_manager_proto_rawDescGZIP() []byte {
	file_manager_proto_rawDescOnce.Do(func() {
		file_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_manager_proto_rawDesc), len(file_manager_proto_rawDesc)))
	})
	return file_manager_proto_rawDescData
}

var file_manager_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_manager_proto_goTypes = []any{
	(JobStatus)(0),                // 0: manager.JobStatus
	(*ResourceRequirements)(nil),  // 1: manager.ResourceRequirements
	(*Resources)(nil),             // 2: manager.Resources
	(*PreprocessingConfig)(nil),   // 3: manager.PreprocessingConfig
	(*DataLocations)(nil),         // 4: manager.DataLocations
	(*CSDConfig)(nil),             // 5: manager.CSDConfig
	(*NodeScheduling)(nil),        // 6: manager.NodeScheduling
	(*JobConfig)(nil),             // 7: manager.JobConfig
	(*SubmitJobRequest)(nil),      // 8: manager.SubmitJobRequest
	(*SubmitJobResponse)(nil),     // 9: manager.SubmitJobResponse
	(*GetJobStatusRequest)(nil),   // 10: manager.GetJobStatusRequest
	(*GetJobStatusResponse)(nil),  // 11: manager.GetJobStatusResponse
	(*CancelJobRequest)(nil),      // 12: manager.CancelJobRequest
	(*CancelJobResponse)(nil),     // 13: manager.CancelJobResponse
	(*NodeResources)(nil),         // 14: manager.NodeResources
	(*ListNodesRequest)(nil),      // 15: manager.ListNodesRequest
	(*ListNodesResponse)(nil),     // 16: manager.ListNodesResponse
	nil,                           // 17: manager.NodeScheduling.NodeSelectorEntry
	nil,                           // 18: manager.SubmitJobRequest.LabelsEntry
	nil,                           // 19: manager.SubmitJobRequest.AnnotationsEntry
	(*timestamppb.Timestamp)(nil), // 20: google.protobuf.Timestamp
}
var file_manager_proto_depIdxs = []int32{
	1,  // 0: manager.Resources.requests:type_name -> manager.ResourceRequirements
	1,  // 1: manager.Resources.limits:type_name -> manager.ResourceRequirements
	17, // 2: manager.NodeScheduling.node_selector:type_name -> manager.NodeScheduling.NodeSelectorEntry
	2,  // 3: manager.SubmitJobRequest.resources:type_name -> manager.Resources
	3,  // 4: manager.SubmitJobRequest.preprocessing:type_name -> manager.PreprocessingConfig
	4,  // 5: manager.SubmitJobRequest.data_locations:type_name -> manager.DataLocations
	5,  // 6: manager.SubmitJobRequest.csd:type_name -> manager.CSDConfig
	6,  // 7: manager.SubmitJobRequest.node_scheduling:type_name -> manager.NodeScheduling
	7,  // 8: manager.SubmitJobRequest.job_config:type_name -> manager.JobConfig
	18, // 9: manager.SubmitJobRequest.labels:type_name -> manager.SubmitJobRequest.LabelsEntry
	19, // 10: manager.SubmitJobRequest.annotations:type_name -> manager.SubmitJobRequest.AnnotationsEntry
	20, // 11: manager.SubmitJobResponse.submitted_at:type_name -> google.protobuf.Timestamp
	0,  // 12: manager.GetJobStatusResponse.status:type_name -> manager.JobStatus
	20, // 13: manager.GetJobStatusResponse.start_time:type_name -> google.protobuf.Timestamp
	20, // 14: manager.GetJobStatusResponse.completion_time:type_name -> google.protobuf.Timestamp
	20, // 15: manager.CancelJobResponse.cancelled_at:type_name -> google.protobuf.Timestamp
	14, // 16: manager.ListNodesResponse.nodes:type_name -> manager.NodeResources
	8,  // 17: manager.InstorageManager.SubmitJob:input_type -> manager.SubmitJobRequest
	10, // 18: manager.InstorageManager.GetJobStatus:input_type -> manager.GetJobStatusRequest
	12, // 19: manager.InstorageManager.CancelJob:input_type -> manager.CancelJobRequest
	15, // 20: manager.InstorageManager.ListNodes:input_type -> manager.ListNodesRequest
	9,  // 21: manager.InstorageManager.SubmitJob:output_type -> manager.SubmitJobResponse
	11, // 22: manager.InstorageManager.GetJobStatus:output_type -> manager.GetJobStatusResponse
	13, // 23: manager.InstorageManager.CancelJob:output_type -> manager.CancelJobResponse
	16, // 24: manager.InstorageManager.ListNodes:output_type -> manager.ListNodesResponse
	21, // [21:25] is the sub-list for method output_type
	17, // [17:21] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_manager_proto_init() }
func file_manager_proto_init() {
	if File_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_manager_proto_rawDesc), len(file_manager_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_manager_proto_goTypes,
		DependencyIndexes: file_manager_proto_depIdxs,
		EnumInfos:         file_manager_proto_enumTypes,
		MessageInfos:      file_manager_proto_msgTypes,
	}.Build()
	File_manager_proto = out.File
	file_manager_proto_goTypes = nil
	file_manager_proto_depIdxs = nil
}
